#!/usr/bin/env bash
# Negative: add a comment that contains "generate" but is NOT a //go:generate directive.
set -euo pipefail
cat > main.go <<'EOF'
package main

// This code is auto-generated by the build tool.
func main() {
	println("hello")
}
EOF
